# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Charlotte Godley
description:         'A blog about software engineering'
url:                 http://blog.charlottegodley.co.uk
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Charlotte Godley
  url:               https://twitter.com/charwarz
  email:             me@charlottegodley.co.uk

# Custom vars
version:             1.0.0
